export { default as authService } from "./authService";
export { default as discoverService } from "./discoverService";
export { default as gameService } from "./gameService";
export { default as genreService } from "./genreService";
export { default as preferenceService } from "./preferencesService";
export { default as recommendationService } from "./recommendationService";
export { default as searchService } from "./searchService";
export { default as tagService } from "./tagService";
export { default as reviewService } from "./reviewService"
export { default as profileService } from "./profileService"