export const CATEGORY_CONFIG = [
  {
    id: "free-to-play",
    name: "Free to Play",
    icon: "🎮",
    color: "green",
    apiGenres: ["free to play"],
    description: "Games available without upfront purchase.",
  },
  {
    id: "action",
    name: "Action",
    icon: "⚡",
    color: "red",
    apiGenres: ["action"],
    description: "Fast-paced combat and reflex-heavy games.",
  },
  {
    id: "adventure",
    name: "Adventure",
    icon: "🧭",
    color: "amber",
    apiGenres: ["adventure"],
    description: "Exploration, story, and discovery-focused games.",
  },
  {
    id: "early-access",
    name: "Early Access",
    icon: "🚧",
    color: "amber",
    apiGenres: ["early access"],
    description: "Games still actively evolving during development.",
  },
  {
    id: "animation",
    name: "Animation",
    icon: "🎞️",
    color: "pink",
    apiGenres: ["animation and modeling"],
    description: "Animation, modeling, and visual production tools.",
  },
  {
    id: "casual",
    name: "Casual",
    icon: "🌿",
    color: "green",
    apiGenres: ["casual"],
    description: "Light, accessible, and relaxed games.",
  },
  {
    id: "illustration",
    name: "Illustration",
    icon: "🎨",
    color: "pink",
    apiGenres: ["design and illustration"],
    description: "Design, drawing, and illustration software.",
  },
  {
    id: "documentary",
    name: "Documentary",
    icon: "🎬",
    color: "gray",
    apiGenres: ["documentary"],
    description: "Documentary and media-based experiences.",
  },
  {
    id: "gore",
    name: "Gore",
    icon: "💀",
    color: "red",
    apiGenres: ["gore"],
    description: "Graphic and intense violent content.",
  },
  {
    id: "indie",
    name: "Indie",
    icon: "✨",
    color: "violet",
    apiGenres: ["indie"],
    description: "Independent games from smaller studios.",
  },
  {
    id: "mmorpg",
    name: "MMORPG",
    icon: "🌐",
    color: "blue",
    apiGenres: ["massively multiplayer"],
    description: "Large online multiplayer worlds.",
  },
  {
    id: "mature",
    name: "Mature",
    icon: "🔞",
    color: "red",
    apiGenres: ["nudity", "sexual content"],
    description: "Mature or adult-oriented content categories.",
  },
  {
    id: "racing",
    name: "Racing",
    icon: "🏁",
    color: "amber",
    apiGenres: ["racing"],
    description: "Driving, speed, and motorsport games.",
  },
  {
    id: "rpg",
    name: "RPG",
    icon: "⚔️",
    color: "violet",
    apiGenres: ["rpg"],
    description: "Role-playing games with progression systems.",
  },
  {
    id: "simulation",
    name: "Simulation",
    icon: "🛠️",
    color: "blue",
    apiGenres: ["simulation"],
    description: "Systems, management, and realistic simulations.",
  },
  {
    id: "sports",
    name: "Sport",
    icon: "⚽",
    color: "green",
    apiGenres: ["sports"],
    description: "Sports and competitive athletic games.",
  },
  {
    id: "strategy",
    name: "Strategy",
    icon: "♟️",
    color: "blue",
    apiGenres: ["strategy"],
    description: "Planning, tactics, and decision-based games.",
  },
  {
    id: "learning",
    name: "Learning",
    icon: "📘",
    color: "blue",
    apiGenres: ["education", "tutorial", "software training"],
    description: "Educational, tutorial, and training content.",
  },
  {
    id: "creative-tools",
    name: "Creative Tools",
    icon: "🧩",
    color: "pink",
    apiGenres: [
      "game development",
      "photo editing",
      "audio production",
      "video production",
      "web publishing",
    ],
    description: "Tools for creating games, media, and web content.",
  },
  {
    id: "business-utilities",
    name: "Business & Utilities",
    icon: "📊",
    color: "gray",
    apiGenres: ["accounting", "utilities"],
    description: "Productivity, business, and utility software.",
  },
  {
    id: "violent",
    name: "Violent",
    icon: "🔥",
    color: "red",
    apiGenres: ["violent"],
    description: "Games with violent or intense action content.",
  },
];
